# Generated by Django 5.1.1 on 2024-09-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormFields",
            fields=[
                ("field_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "field_name",
                    models.CharField(db_column="field_name", max_length=100),
                ),
                ("field_type", models.CharField(db_column="field_type", max_length=50)),
                (
                    "is_reuired",
                    models.BooleanField(db_column="is_reuired", default=False),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="custom_form",
                        to="user_feedback.customforms",
                    ),
                ),
            ],
            options={
                "db_table": "FormFields",
            },
        ),
        migrations.CreateModel(
            name="Options",
            fields=[
                ("option_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "option_lable",
                    models.CharField(db_column="option_lable", max_length=100),
                ),
                (
                    "option_value",
                    models.CharField(db_column="option_value", max_length=100),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="option_form",
                        to="user_feedback.formfields",
                    ),
                ),
            ],
            options={
                "db_table": "Options",
            },
        ),
        migrations.CreateModel(
            name="FormResponses",
            fields=[
                ("response_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "response_text",
                    models.TextField(
                        db_column="response_text", max_length=500, null=True
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="field_form",
                        to="user_feedback.formfields",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="filled_response",
                        to="user_feedback.user",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="form_response",
                        to="user_feedback.customforms",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="selected_option",
                        to="user_feedback.options",
                    ),
                ),
            ],
            options={
                "db_table": "FormResponses",
            },
        ),
    ]
