# Generated by Django 5.1.1 on 2024-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_feedback", "0002_formfields_options_formresponses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(db_column="username", max_length=100),
        ),
    ]
