# Generated by Django 5.1.1 on 2024-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_feedback", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfields",
            name="order",
            field=models.IntegerField(db_column="order", default=0),
        ),
    ]
