# Generated by Django 5.1.1 on 2024-09-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_feedback", "0004_add_order_in_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formfields",
            old_name="is_reuired",
            new_name="is_required",
        ),
    ]
