# Generated by Django 5.1.1 on 2024-09-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_feedback", "0005_rename_is_reuired_formfields_is_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfields",
            name="is_required",
            field=models.BooleanField(db_column="is_required", default=False),
        ),
    ]
