# Generated by Django 5.1.1 on 2024-09-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_feedback", "0006_alter_formfields_is_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user_feedback.formfields",),
        ),
        migrations.CreateModel(
            name="Form",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user_feedback.customforms",),
        ),
        migrations.CreateModel(
            name="Option",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user_feedback.options",),
        ),
        migrations.CreateModel(
            name="Response",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user_feedback.formresponses",),
        ),
        migrations.AddField(
            model_name="formresponses",
            name="response_uuid",
            field=models.CharField(
                db_column="response_uuid", default="", max_length=100
            ),
        ),
    ]
