# Generated by Django 5.2.1 on 2025-05-17 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_feedback", "0007_field_form_option_response_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formresponses",
            name="field",
        ),
        migrations.RemoveField(
            model_name="formresponses",
            name="option",
        ),
        migrations.RemoveField(
            model_name="formresponses",
            name="response_text",
        ),
        migrations.RemoveField(
            model_name="formresponses",
            name="response_uuid",
        ),
        migrations.CreateModel(
            name="OptionFieldResponses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="related_fields_options",
                        to="user_feedback.formfields",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="option_field_response",
                        to="user_feedback.customforms",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="related_response",
                        to="user_feedback.formresponses",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="related_options",
                        to="user_feedback.options",
                    ),
                ),
            ],
            options={
                "db_table": "OptionFieldResponses",
            },
        ),
        migrations.CreateModel(
            name="TextFieldResponses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField(blank=True, null=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="related_fields",
                        to="user_feedback.formfields",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="forms_set",
                        to="user_feedback.customforms",
                    ),
                ),
            ],
            options={
                "db_table": "TextFieldResponses",
            },
        ),
    ]
