# Generated by Django 5.2.1 on 2025-05-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_feedback", "0008_remove_formresponses_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="textfieldresponses",
            name="response_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="optionfieldresponses",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_response_option",
                to="user_feedback.formresponses",
            ),
        ),
        migrations.AlterField(
            model_name="textfieldresponses",
            name="response",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_response",
                to="user_feedback.formresponses",
            ),
        ),
    ]
