# Generated by Django 5.2.1 on 2025-05-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_feedback", "0009_textfieldresponses_response_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customforms",
            name="form_title",
            field=models.CharField(db_column="form_title", max_length=50),
        ),
    ]
